#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Assign values if IB vCenter action selected
  set_fact:
    vcenter_type: ib
  tags:
    - create_ib_datacenter_create_task
    - create_ib_datacenter_destroy_task

- name: Assign values if OOB vCenter action selected
  set_fact:
    vcenter_type: oob
  tags:
    - create_oob_datacenter_create_task
    - create_oob_datacenter_destroy_task

- name: Create the task to create the datacenter in the IB vCenter
  template: src=../templates/create_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/create_ib_datacenter.yml
  tags:
    - create_ib_datacenter_create_task

- name: Create the task to destroy the datacenter in the IB vCenter
  template: src=../templates/destroy_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/destroy_ib_datacenter.yml
  tags:
    - create_ib_datacenter_destroy_task

- name: Create the task to create the datacenter in the OOB vCenter
  template: src=../templates/create_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/create_oob_datacenter.yml
  tags:
    - create_oob_datacenter_create_task

- name: Create the task to destroy the datacenter in the OOB vCenter
  template: src=../templates/destroy_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/destroy_oob_datacenter.yml
  tags:
    - create_oob_datacenter_destroy_task

- name: Create datacenter in the IB vCenter
  include: create_ib_datacenter.yml
  tags:
    - create_ib_datacenter

- name: Create datacenter in the OOB vCenter
  include: create_oob_datacenter.yml
  tags:
    - create_oob_datacenter

- name: Destroy datacenter in the IB vCenter
  include: destroy_ib_datacenter.yml
  tags:
    - destroy_ib_datacenter

- name: Create datacenter in the OOB vCenter
  include: destroy_oob_datacenter.yml
  tags:
    - destroy_oob_datacenter
